// TODO: make this work.

// // Generated by ts-to-zod
// import { z } from 'zod';
// import {
//   BvShareEstID,
//   BvShareNumEstID,
//   CashOperEstID,
//   CashOperNumEstID,
//   Country,
//   Currency,
//   CurrencySymbol,
//   DpsEstID,
//   DpsNumEstID,
//   EbitdaEstID,
//   EpsNormEstID,
//   EpsNormNumEstID,
//   EpsReportedEstID,
//   EpsReportedHighEstID,
//   EpsReportedLowEstID,
//   EpsReportedNumEstID,
//   EstActEbitdaID,
//   EstActEpsReportedID,
//   EstActNIReportedID,
//   EstActRevID,
//   ExchangeCountryISO3,
//   ExchangeName,
//   ExchangeSymbol,
//   FcfEstID,
//   FcfNumEstID,
//   GrossMarginEstID,
//   NIEstID,
//   NINumEstID,
//   NIReportedEstID,
//   NIReportedHighEstID,
//   NIReportedLowEstID,
//   NIReportedNumEstID,
//   NavEstID,
//   NavNumEstID,
//   OwnerType,
//   PastID,
//   Prefix,
//   ProTitle,
//   ReportingUnitText,
//   ReturnEquityEstID,
//   ReturnEquityNumEstID,
//   RevenueEstID,
//   RevenueHighEstID,
//   RevenueLowEstID,
//   RevenueNumEstID,
//   TraType,
//   TransactionTypeDescription,
// } from './simply-wall-street-crawl-company-page-data.types';

// export const exchangeSymbolSchema = z.nativeEnum(ExchangeSymbol);

// export const purpleDividendSchema = z.object({
//   current: z.number(),
//   future: z.number().nullable(),
//   upcoming: z.boolean(),
//   ex_date: z.null(),
// });

// export const dataFutureSchema = z.object({
//   growth_1y: z.number().nullable(),
//   growth_3y: z.number().nullable(),
//   roe_1y: z.number().nullable(),
//   roe_3y: z.number(),
// });

// export const fluffyPastSchema = z.object({
//   growth_1y: z.number(),
//   growth_5y: z.number().nullable(),
// });

// export const scoresSchema = z.object({
//   value: z.number(),
//   income: z.number(),
//   health: z.number(),
//   past: z.number(),
//   future: z.number(),
//   management: z.number(),
//   misc: z.number(),
//   total: z.number(),
//   sentence: z.string(),
// });

// export const analysisDividendSchema = z.object({
//   dividend_yield: z.number(),
//   dividend_yield_future: z.number().nullable(),
//   dividend_volatility: z.boolean().nullable(),
//   dividend_paying_years: z.number(),
//   payout_ratio: z.number(),
//   payout_ratio_3y: z.number().nullable(),
//   historical_dividend_yield: z.record(z.number()),
//   historical_dividend_payments: z.record(z.number()),
//   merged_future_dividends_per_share: z.union([
//     z.array(z.any()),
//     z.record(z.number()),
//   ]),
//   merged_future_yield: z.union([z.array(z.any()), z.record(z.number())]),
//   upcoming_dividend: z.array(z.any()),
//   dividend_yield_growth_annual: z.number().nullable(),
//   first_payment: z.number().nullable(),
//   last_payment: z.number().nullable(),
//   industry_analysis: z.array(z.any()),
//   buyback_yield: z.number(),
//   total_shareholder_yield: z.number(),
//   payout_ratio_median_3yr: z.number().nullable(),
//   dividend_payments_growth_annual: z.number().nullable(),
//   dividend_payments_single_growth_1y: z.number().nullable(),
//   dividend_payments_single_growth_3y: z.number().nullable(),
//   dividend_payments_single_growth_5y: z.number().nullable(),
//   dividend_payments_ltm: z.number().nullable(),
//   payout_ratio_history: z.record(z.number()),
//   cash_payout_ratio: z.number(),
// });

// export const analysisFutureSchema = z.object({
//   return_on_equity_1y: z.number().nullable(),
//   return_on_equity_3y: z.number().nullable(),
//   earnings_per_share_growth_1y: z.number().nullable(),
//   earnings_per_share_growth_3y: z.number().nullable(),
//   earnings_per_share_1y: z.number().nullable(),
//   earnings_per_share_2y: z.number().nullable(),
//   earnings_per_share_3y: z.number().nullable(),
//   revenue_growth_1y: z.number().nullable(),
//   revenue_growth_2y: z.number().nullable(),
//   revenue_growth_3y: z.number().nullable(),
//   revenue_1y: z.number().nullable(),
//   revenue_2y: z.number().nullable(),
//   revenue_3y: z.number().nullable(),
//   cash_ops_growth_1y: z.number().nullable(),
//   cash_ops_growth_2y: z.number().nullable(),
//   cash_ops_growth_3y: z.null(),
//   cash_ops_1y: z.number().nullable(),
//   cash_ops_2y: z.number().nullable(),
//   cash_ops_3y: z.null(),
//   net_income_growth_1y: z.number().nullable(),
//   net_income_growth_2y: z.number().nullable(),
//   net_income_growth_3y: z.number().nullable(),
//   net_income_1y: z.number().nullable(),
//   net_income_2y: z.number().nullable(),
//   net_income_3y: z.number().nullable(),
//   minimum_earnings_growth: z.number(),
//   merged_future_earnings_per_share: z.union([
//     z.array(z.any()),
//     z.record(z.number()),
//   ]),
//   merged_future_earnings_per_share_high: z.union([
//     z.array(z.any()),
//     z.record(z.number()),
//   ]),
//   merged_future_earnings_per_share_low: z.union([
//     z.array(z.any()),
//     z.record(z.number()),
//   ]),
//   merged_future_revenue: z.union([z.array(z.any()), z.record(z.number())]),
//   merged_future_cash_operations: z.union([
//     z.array(z.any()),
//     z.record(z.number()),
//   ]),
//   merged_future_net_income: z.union([z.array(z.any()), z.record(z.number())]),
//   earnings_per_share_growth_annual: z.number().nullable(),
//   revenue_growth_annual: z.number().nullable(),
//   cash_ops_growth_annual: z.number().nullable(),
//   net_income_growth_annual: z.number().nullable(),
//   industry_analysis: z.array(z.any()),
//   merged_future_ebitda: z.union([z.array(z.any()), z.record(z.number())]),
//   ebitda_1y: z.number().nullable(),
//   ebitda_growth_1y: z.number().nullable(),
//   forward_pe_1y: z.number().nullable(),
//   forward_price_to_sales_1y: z.number().nullable(),
//   forward_ev_to_ebitda_1y: z.number().nullable(),
//   forward_ev_to_sales_1y: z.number().nullable(),
//   gross_profit_margin_1y: z.number().nullable(),
//   net_income_margin_1y: z.number().nullable(),
//   merged_future_revenue_high: z.union([z.array(z.any()), z.record(z.number())]),
//   merged_future_revenue_low: z.union([z.array(z.any()), z.record(z.number())]),
//   merged_future_net_income_high: z.union([
//     z.array(z.any()),
//     z.record(z.number()),
//   ]),
//   merged_future_net_income_low: z.union([
//     z.array(z.any()),
//     z.record(z.number()),
//   ]),
//   next_earnings_release: z.null(),
//   last_revenue_estimate_confirmed: z.number().nullable(),
//   last_net_income_estimate_confirmed: z.number().nullable(),
// });

// export const analysisManagementSchema = z.object({
//   management_tenure: z.number().nullable(),
//   board_tenure: z.number(),
//   management_age: z.number(),
//   board_age: z.number(),
//   insider_buying_ratio: z.number().nullable(),
//   total_shares_bought: z.number(),
//   total_shares_sold: z.number(),
//   total_employees: z.number().nullable(),
//   ceo_compensation: z.array(z.any()),
//   ceo_salary_growth_1y: z.null(),
//   industry_analysis: z.array(z.any()),
//   ceo_salary_growth_annual: z.null(),
//   ceo_compensation_total: z.null(),
//   ceo_compensation_salary: z.null(),
//   ceo_compensation_salary_usd: z.null(),
//   ceo_compensation_total_usd: z.null(),
//   ceo_compensation_salary_history: z.array(z.any()),
//   ceo_salary_fraction: z.null(),
//   total_board_members_count: z.number(),
//   independent_board_members_count: z.number(),
//   independent_board_members_ratio: z.number(),
// });

// export const analysisMiscSchema = z.object({
//   min_price: z.number(),
//   max_price: z.number(),
//   min_price_52w: z.number(),
//   max_price_52w: z.number(),
//   price_spread: z.number(),
//   is_volatile: z.boolean(),
//   analyst_count: z.number().nullable(),
//   is_fund: z.boolean(),
//   industry_analysis: z.array(z.any()),
//   days_since_last_trade: z.number(),
//   shares_outstanding_single_growth_1y: z.number().nullable(),
//   shares_outstanding_single_growth_5y: z.number().nullable(),
//   daily_return_standard_deviation_90d: z.number(),
//   daily_return_standard_deviation_1y: z.number(),
// });

// export const netOperatingAssetsLtmHistorySchema = z.object({
//   '0': z.number(),
//   '-1': z.number(),
//   '-2': z.number(),
//   '-3': z.number(),
// });

// export const aggregateAccrualsLtmHistorySchema = z.object({
//   '0': z.number(),
//   '-1': z.number(),
//   '-2': z.number(),
//   '-3': z.number().nullable(),
// });

// export const accrualRatioFromCashflowLtmHistorySchema = z.object({
//   '0': z.number(),
//   '-1': z.number(),
//   '-2': z.number(),
// });

// export const ltmHistorySchema = z.object({
//   '0': z.number(),
//   '-1': z.number(),
//   '-2': z.number(),
//   '-3': z.number().nullable(),
//   '-4': z.number().nullable(),
//   '-5': z.number().nullable(),
// });

// export const eLtmHistorySchema = z.object({
//   '0': z.number(),
//   '-1': z.number(),
//   '-2': z.number(),
//   '-3': z.number().nullable(),
//   '-4': z.number().nullable(),
//   '-5': z.number().nullable(),
//   '-6': z.number().nullable(),
//   '-7': z.number().nullable(),
//   '-8': z.number().nullable(),
//   '-9': z.number().nullable(),
//   '-10': z.number().nullable(),
// });

// export const industryAnalysisClassSchema = z.object({
//   d_a_expense: z.number().nullable(),
//   r_d_expense: z.number().nullable(),
//   non_op_expense: z.number(),
//   sales_marketing: z.number().nullable(),
//   revenue_segments: z.record(z.number()),
//   stock_based_comp: z.number().nullable(),
//   general_administrative: z.number(),
//   selling_general_admin_expenses: z.number(),
// });

// export const geographicRevenueSegmentsSchema = z.object({
//   Japan: z.number().optional(),
//   Europe: z.number().optional(),
//   America: z.number().optional(),
//   'Rest of Asia/Others': z.number().optional(),
//   Philippines: z.number().optional(),
//   Foreign: z.number().optional(),
//   Others: z.number().optional(),
//   Eliminations: z.number().optional(),
//   'United States': z.number().optional(),
// });

// export const countrySchema = z.nativeEnum(Country);

// export const dividendDiscountSchema = z.object({
//   dps: z.number().nullable(),
//   roe: z.number().nullable(),
//   payout: z.number().nullable(),
//   ddm_growth: z.number().nullable(),
//   ddm_source: z.string().nullable(),
//   expected_growth: z.number().nullable(),
// });

// export const reportingUnitTextSchema = z.nativeEnum(ReportingUnitText);

// export const firstStageSchema = z.object({
//   data: z.number(),
//   source: z.string(),
//   discounted: z.number(),
// });

// export const allSchema = z.object({
//   industryId: z.number(),
//   countryIso: countrySchema,
//   name: z.string(),
//   valueScore: z.number(),
//   dividendsScore: z.number(),
//   futurePerformanceScore: z.number(),
//   healthScore: z.number(),
//   pastPerformanceScore: z.number(),
//   totalScore: z.number(),
//   sharePrice: z.number(),
//   marketCap: z.number(),
//   intrinsicDiscount: z.number(),
//   analystCount: z.number(),
//   PE: z.number(),
//   PB: z.number(),
//   PEG: z.number(),
//   futureOneYearGrowth: z.number(),
//   futureThreeYearGrowth: z.number(),
//   futureOneYearROE: z.null(),
//   futureThreeYearROE: z.null(),
//   pastOneYearGrowth: z.number(),
//   pastFiveYearGrowth: z.number(),
//   ROE: z.number(),
//   ROA: z.number(),
//   dividendYield: z.number(),
//   futureDividendYield: z.number(),
//   payoutRatio: z.null(),
//   EPS: z.number(),
//   insiderBuying: z.number(),
//   debtEquity: z.number(),
//   leveredBeta: z.number(),
//   unleveredBeta: z.number(),
//   totalBaseCount: z.number(),
//   profitableCount: z.number(),
//   analystCoverageCount: z.number(),
//   dividendCount: z.number(),
//   betaCount: z.number(),
//   earningsPerShareGrowthAnnual: z.number(),
//   netIncomeGrowthAnnual: z.number(),
//   cashOpsGrowthAnnual: z.number(),
//   revenueGrowthAnnual: z.number(),
//   leveredBetaMedian: z.number(),
// });

// export const companyInfoSchema = z.object({
//   url: z.string(),
//   city: z.string(),
//   name: z.string(),
//   type: z.string(),
//   state: z.null(),
//   address: z.string(),
//   country: z.string(),
//   is_fund: z.boolean(),
//   address2: z.string(),
//   zip_code: z.number().nullable(),
//   company_id: z.number(),
//   short_name: z.string(),
//   country_iso: countrySchema,
//   description: z.string(),
//   isin_symbol: z.string(),
//   status_type: z.string(),
//   year_founded: z.number().nullable(),
//   ticker_symbol: z.string(),
//   unique_symbol: z.string(),
//   exchange_symbol: exchangeSymbolSchema,
//   trading_item_id: z.number(),
//   short_description: z.string(),
//   short_name_plural: z.string(),
//   exchange_symbol_filtered: exchangeSymbolSchema,
// });

// export const marketCapSchema = z.object({
//   usd: z.number(),
//   listing: z.number(),
//   primary: z.number(),
//   reported: z.number(),
//   market_cap_band: z.string(),
//   shares_outstanding: z.number(),
//   original_market_cap: z.null(),
//   trading_item_to_primary_ratio: z.number(),
//   total_enterprise_value_reported: z.number(),
//   shares_outstanding_common_equity: z.number(),
//   relative_listing_shares_outstanding: z.number(),
// });

// export const currencySchema = z.nativeEnum(Currency);

// export const currencySymbolSchema = z.nativeEnum(CurrencySymbol);

// export const chainSchema = z.object({
//   date: z.number(),
//   days: z.number(),
//   value: z.number().nullable(),
//   end_date: z.number(),
//   avg_yield: z.number(),
//   raw_value: z.number(),
// });

// export const pastPastSchema = z.object({
//   date: z.number(),
//   amount: z.number(),
//   pay_date: z.number(),
//   record_date: z.number(),
//   currency_iso: currencySchema,
//   split_adjusted_amount: z.number(),
//   reporting_currency_amount: z.number(),
// });

// export const priceTargetEstSchema = z.object({
//   id: z.string(),
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const tNumEstSchema = z.object({
//   id: z.string(),
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const ffoAdjReitEstSchema = z.object({
//   id: z.string(),
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const bvShareEstIDSchema = z.nativeEnum(BvShareEstID);

// export const bvShareNumEstIDSchema = z.nativeEnum(BvShareNumEstID);

// export const cashOperEstIDSchema = z.nativeEnum(CashOperEstID);

// export const cashOperNumEstIDSchema = z.nativeEnum(CashOperNumEstID);

// export const dpsEstIDSchema = z.nativeEnum(DpsEstID);

// export const dpsNumEstIDSchema = z.nativeEnum(DpsNumEstID);

// export const ebitdaEstIDSchema = z.nativeEnum(EbitdaEstID);

// export const epsNormEstIDSchema = z.nativeEnum(EpsNormEstID);

// export const epsNormNumEstIDSchema = z.nativeEnum(EpsNormNumEstID);

// export const epsReportedEstIDSchema = z.nativeEnum(EpsReportedEstID);

// export const epsReportedHighEstIDSchema = z.nativeEnum(EpsReportedHighEstID);

// export const epsReportedLowEstIDSchema = z.nativeEnum(EpsReportedLowEstID);

// export const epsReportedNumEstIDSchema = z.nativeEnum(EpsReportedNumEstID);

// export const estActEbitdaIDSchema = z.nativeEnum(EstActEbitdaID);

// export const estActEpsReportedIDSchema = z.nativeEnum(EstActEpsReportedID);

// export const estActNIReportedIDSchema = z.nativeEnum(EstActNIReportedID);

// export const estActRevIDSchema = z.nativeEnum(EstActRevID);

// export const fcfEstIDSchema = z.nativeEnum(FcfEstID);

// export const fcfNumEstIDSchema = z.nativeEnum(FcfNumEstID);

// export const grossMarginEstIDSchema = z.nativeEnum(GrossMarginEstID);

// export const navEstIDSchema = z.nativeEnum(NavEstID);

// export const navNumEstIDSchema = z.nativeEnum(NavNumEstID);

// export const nIEstIDSchema = z.nativeEnum(NIEstID);

// export const nINumEstIDSchema = z.nativeEnum(NINumEstID);

// export const nIReportedEstIDSchema = z.nativeEnum(NIReportedEstID);

// export const nIReportedHighEstIDSchema = z.nativeEnum(NIReportedHighEstID);

// export const nIReportedLowEstIDSchema = z.nativeEnum(NIReportedLowEstID);

// export const nIReportedNumEstIDSchema = z.nativeEnum(NIReportedNumEstID);

// export const returnEquityEstIDSchema = z.nativeEnum(ReturnEquityEstID);

// export const returnEquityNumEstIDSchema = z.nativeEnum(ReturnEquityNumEstID);

// export const revenueEstIDSchema = z.nativeEnum(RevenueEstID);

// export const revenueHighEstIDSchema = z.nativeEnum(RevenueHighEstID);

// export const revenueLowEstIDSchema = z.nativeEnum(RevenueLowEstID);

// export const revenueNumEstIDSchema = z.nativeEnum(RevenueNumEstID);

// export const primarySchema = z.object({
//   sic: z.null(),
//   name: z.string(),
//   level: z.number(),
//   sic_name: z.string(),
//   sub_type_id: z.number(),
// });

// export const tertiarySchema = z.object({
//   sic: z.number().nullable(),
//   name: z.string(),
//   level: z.number(),
//   sic_name: z.string(),
//   sub_type_id: z.number(),
// });

// export const traTypeSchema = z.nativeEnum(TraType);

// export const the3BuySchema = z.object({
//   avg_price: z.number(),
//   month_diff: z.number(),
//   trade_type: traTypeSchema,
//   security_id: z.number(),
//   total_shares: z.number(),
//   total_trades: z.number(),
//   company_names: z.array(z.string()),
//   unique_owners: z.number(),
//   individual_ids: z.array(z.number()),
//   individual_names: z.array(z.string()),
//   total_trans_value: z.number(),
//   total_company_shares: z.number(),
//   total_individual_shares: z.number(),
// });

// export const transactionTypeDescriptionSchema = z.nativeEnum(
//   TransactionTypeDescription
// );

// export const ownerTypeSchema = z.nativeEnum(OwnerType);

// export const exchangeNameSchema = z.nativeEnum(ExchangeName);

// export const exchangeCountryISO3Schema = z.nativeEnum(ExchangeCountryISO3);

// export const prefixSchema = z.nativeEnum(Prefix);

// export const proTitleSchema = z.nativeEnum(ProTitle);

// export const managementValueSchema = z.object({
//   id: z.number(),
//   age: z.number().nullable(),
//   rank: z.number(),
//   title: z.string(),
//   prefix: prefixSchema.nullable(),
//   pro_id: z.number(),
//   suffix: z.string().nullable(),
//   tenure: z.number().nullable(),
//   key_exec: z.boolean(),
//   only_one: z.boolean(),
//   pro_rank: z.number(),
//   biography: z.string(),
//   last_name: z.string(),
//   pro_title: z.string(),
//   specialty: z.null(),
//   year_born: z.number().nullable(),
//   board_flag: z.boolean(),
//   board_rank: z.number().nullable(),
//   first_name: z.string(),
//   pro_member: z.boolean(),
//   salutation: z.string(),
//   start_date: z.number().nullable(),
//   currency_id: z.null(),
//   middle_name: z.string().nullable(),
//   shares_held: z.number().nullable(),
//   short_title: z.string(),
//   board_member: z.boolean(),
//   compensation: z.null(),
//   holding_date: z.number().nullable(),
//   options_held: z.number().nullable(),
//   top_key_exec: z.boolean(),
//   shares_changed: z.number().nullable(),
//   rank_shares_held: z.number().nullable(),
//   rank_shares_sold: z.number().nullable(),
//   rank_shares_bought: z.number().nullable(),
//   percent_shares_changed: z.number().nullable(),
//   percent_of_shares_outstanding: z.number().nullable(),
// });

// export const ownershipSchema = z.object({
//   shares_held: z.number(),
//   owner_type_id: z.number(),
//   owner_type_name: z.string(),
//   owned_company_id: z.number(),
// });

// export const pastIDSchema = z.nativeEnum(PastID);

// export const historySchema = z.object({
//   ask: z.number(),
//   bid: z.number(),
//   low: z.number().nullable(),
//   mid: z.number(),
//   date: z.number(),
//   open: z.number().nullable(),
//   close: z.number(),
//   volume: z.number().nullable(),
//   currency: currencySchema,
//   adjustment_factor: z.number(),
// });

// export const return90DSchema = z.object({
//   ask: z.number(),
//   bid: z.number(),
//   low: z.number(),
//   mid: z.number(),
//   date: z.number(),
//   open: z.number(),
//   close: z.number(),
//   volume: z.number(),
//   currency: currencySchema,
//   adjustment_factor: z.number(),
// });

// export const growthStatementDataSchema = z.object({
//   market: z.string(),
//   last_payment: z.number(),
//   first_payment: z.number(),
//   min_threshold: z.number(),
//   dividend_yield: z.number(),
//   dividend_paying_years: z.number(),
// });

// export const payoutStatementDataSchema = z.object({
//   market: z.string(),
//   threshold: z.number(),
//   payout_ratio: z.number(),
//   min_threshold: z.number(),
//   dividend_yield: z.number(),
//   payout_ratio_inverse: z.number().nullable(),
// });

// export const payoutStatement3YDataSchema = z.object({
//   market: z.string(),
//   threshold: z.number(),
//   min_threshold: z.number(),
//   payout_ratio_3y: z.number().nullable(),
//   dividend_yield_future: z.number(),
//   payout_ratio_3y_inverse: z.number().nullable(),
// });

// export const volatilityStatementDataSchema = z.object({
//   market: z.string(),
//   min_threshold: z.number(),
//   dividend_yield: z.number(),
//   dividend_volatility: z.boolean(),
//   dividend_paying_years: z.number(),
// });

// export const yieldLowRiskStatementDataSchema = z.object({
//   market: z.string(),
//   low_risk_rate: z.number(),
//   dividend_yield: z.number(),
// });

// export const yieldMarketTopStatementDataSchema = z.object({
//   market: z.string(),
//   dividend_yield: z.number(),
//   top_top_top_of_the_best: z.number(),
// });

// export const meaninglessFutureStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: z.record(z.number().nullable()),
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const cash2YStatementDataSchema = z.object({
//   cash_ops_2y: z.number().nullable(),
//   cash_ops_now: z.number(),
//   cash_ops_growth_2y: z.number().nullable(),
// });

// export const earningsHighGrowthDataSchema = z.object({
//   net_income_now: z.number(),
//   minimum_threshold: z.number(),
//   maximum_net_income: z.number(),
//   net_income_growth_annual: z.number(),
// });

// export const earningsVsMarketAverageDataSchema = z.object({
//   country: z.string(),
//   market_average: z.number(),
//   maximum_net_income: z.number(),
//   net_income_growth_annual: z.number(),
//   net_income_growth_market: z.number(),
// });

// export const fundamentalGrowthMethodStatementDataSchema = z.object({
//   growth_result: z.boolean(),
//   fundamental_growth_inputs: z.boolean(),
// });

// export const growth1YStatementDataSchema = z.object({
//   minimum_threshold: z.number(),
//   earnings_per_share_1y: z.number(),
//   earnings_per_share_now: z.number(),
//   earnings_per_share_growth_1y: z.number().nullable(),
// });

// export const growth3YStatementDataSchema = z.object({
//   minimum_threshold: z.number(),
//   earnings_per_share_3y: z.number().nullable(),
//   earnings_per_share_now: z.number(),
//   earnings_per_share_growth_3y: z.number().nullable(),
// });

// export const netIncome2YStatementDataSchema = z.object({
//   net_income_2y: z.number(),
//   net_income_now: z.number(),
//   net_income_growth_2y: z.number().nullable(),
// });

// export const projectedROEBenchStatementDataSchema = z.object({
//   return_on_equity_3y: z.number(),
// });

// export const projectedROEIndustryStatementDataSchema = z.object({
//   industry_name: z.string(),
//   return_on_equity_3y: z.number(),
//   return_on_equity_industry: z.number(),
// });

// export const projectedROEStatementDataSchema = z.object({
//   return_on_equity: z.number(),
//   return_on_equity_3y: z.number(),
// });

// export const revenue2YStatementDataSchema = z.object({
//   revenue_2y: z.number(),
//   renenue_now: z.number(),
//   revenue_growth_2y: z.number(),
// });

// export const revenueHighGrowthDataSchema = z.object({
//   minimum_threshold: z.number(),
//   maximum_net_income: z.number(),
//   revenue_growth_annual: z.number(),
// });

// export const revenueVsMarketAverageDataSchema = z.object({
//   country: z.string(),
//   maximum_revenue: z.number(),
//   revenue_growth_annual: z.number(),
//   revenue_growth_market: z.number(),
// });

// export const assetsToLiabsStatementDataSchema = z.object({
//   current_solvency_ratio: z.number(),
// });

// export const cashBurnGrowthStatementDataSchema = z.object({
//   net_income: z.number(),
//   net_income_5y_avg: z.number(),
//   levered_free_cash_flow: z.number(),
//   levered_free_cash_flow_growth_years: z.null(),
//   levered_free_cash_flow_growth_annual: z.number(),
// });

// export const cashBurnStableStatementDataSchema = z.object({
//   net_income: z.number(),
//   net_income_5y_avg: z.number(),
//   levered_free_cash_flow: z.number(),
//   levered_free_cash_flow_stable_years: z.null(),
// });

// export const cashDebtStatementDataSchema = z.object({
//   net_income: z.number(),
//   total_debt: z.number(),
//   net_income_5y_avg: z.number(),
//   levered_free_cash_flow: z.number(),
//   operating_cash_flow_to_total_debt: z.number(),
// });

// export const currentAssetsToDebtStatementDataSchema = z.object({
//   total_debt: z.number(),
//   total_equity: z.number(),
//   current_assets_to_total_debt: z.number(),
// });

// export const currentAssetsToLTLiabsStatementDataSchema = z.object({
//   long_term_liab: z.number(),
//   current_assets_to_long_term_liab: z.number(),
// });

// export const debtGrowthStatementDataSchema = z.object({
//   total_debt: z.number(),
//   total_equity: z.number(),
//   total_debt_max: z.number(),
//   debt_to_equity_ratio: z.number(),
//   debt_to_equity_ratio_past: z.number(),
// });

// export const debtInterestStatementDataSchema = z.object({
//   net_income: z.number(),
//   total_debt: z.number(),
//   net_income_5y_avg: z.number(),
//   earnings_per_share: z.number(),
//   net_interest_cover: z.number().nullable(),
//   levered_free_cash_flow: z.number(),
// });

// export const debtStatementDataSchema = z.object({
//   total_debt: z.number(),
//   total_equity: z.number(),
//   debt_to_equity_ratio: z.number(),
// });

// export const inventoryStatementDataSchema = z.object({
//   fixed_to_total_assets: z.number(),
// });

// export const meaninglessHealthStatementDataSchema = z.object({
//   total_assets: z.number(),
//   total_equity: z.number(),
//   current_assets: z.number(),
//   cast_st_investments: z.number(),
//   debt_to_equity_ratio: z.number(),
//   debt_to_equity_ratio_past: z.number(),
// });

// export const boardTenureStatementDataSchema = z.object({
//   lower_limit: z.number(),
//   upper_limit: z.number(),
//   board_tenure: z.number(),
// });

// export const cEOOverCompensationStatementDataSchema = z.object({
//   market: z.null(),
//   ceo_name: z.string(),
//   median_compensation_usd: z.null(),
//   ceo_compensation_total_usd: z.null(),
// });

// export const cEOSalaryGrowthStatementDataSchema = z.object({
//   ceo_name: z.string(),
//   earnings_per_share: z.number(),
//   ceo_salary_growth_1y: z.null(),
//   earnings_per_share_1y: z.number(),
//   earnings_per_share_growth_1y: z.number(),
// });

// export const insiderTradeStatementDataSchema = z.object({
//   buying_3_month: z.number(),
//   total_ex_3_month: z.number(),
//   buying_3_month_value: z.number(),
//   insider_buying_ratio: z.number().nullable(),
//   selling_3_month_value: z.number(),
//   minimum_value_threshold: z.number(),
// });

// export const proTenureStatementDataSchema = z.object({
//   lower_limit: z.number(),
//   upper_limit: z.number(),
//   management_tenure: z.number(),
// });

// export const analystCoverageStatementDataSchema = z.object({
//   limit: z.number(),
//   analystCount: z.number(),
// });

// export const exchangeTradedFundStatementDataSchema = z.object({
//   is_fund: z.boolean(),
// });

// export const marketCapStatementDataSchema = z.object({
//   threshold: z.number(),
//   marketCapUSD: z.number(),
// });

// export const outDatedDataStatementDataSchema = z.object({
//   days_since_last_update: z.number(),
// });

// export const priceVolatilityStatementDataSchema = z.object({
//   threshold: z.number(),
//   volatility: z.boolean(),
// });

// export const tradingHaltStatementDataSchema = z.object({
//   unique_symbol: z.string(),
//   days_since_last_trade: z.number(),
// });

// export const growth1Y5YStatementDataSchema = z.object({
//   earnings: z.number(),
//   earnings_1y: z.number(),
//   earnings_growth_1y: z.number(),
//   earnings_growth_5y: z.number(),
//   trading_since_years: z.number(),
// });

// export const growth5YStatementDataSchema = z.object({
//   earnings: z.number(),
//   earnings_5y_avg: z.number(),
//   earnings_growth_5y: z.number(),
//   trading_since_years: z.number(),
// });

// export const meaninglessPastStatementDataSchema = z.object({
//   revenue: z.number(),
//   net_income: z.number(),
//   return_on_assets: z.number(),
//   return_on_equity: z.number(),
//   return_on_capital_employed: z.number(),
//   return_on_capital_employed_past: z.number(),
// });

// export const rOAStatementDataSchema = z.object({
//   industry_name: z.string(),
//   return_on_assets: z.number(),
//   return_on_assets_industry: z.number(),
// });

// export const rOCEStatementDataSchema = z.object({
//   net_income: z.number(),
//   total_assets: z.number(),
//   current_liabilities: z.number(),
//   return_on_capital_growth: z.number(),
//   return_on_capital_employed: z.number(),
//   return_on_capital_employed_past: z.number(),
// });

// export const rOEStatementDataSchema = z.object({
//   total_equity: z.number(),
//   return_on_equity: z.number(),
//   total_debt_equity: z.number(),
//   earnings_continued_ops: z.number(),
// });

// export const vsMarketGrowthStatementDataSchema = z.object({
//   earnings: z.number(),
//   earnings_1y: z.number(),
//   industry_name: z.string(),
//   earnings_growth_1y: z.number(),
//   eps_growth_industry: z.number(),
// });

// export const intrinsicStatementDataSchema = z.object({
//   intrinsic_discount: z.number(),
// });

// export const meaninglessDCFStatementDataSchema = z.object({
//   pb: z.number(),
//   pe: z.number(),
//   peg: z.number().nullable(),
//   type: z.string(),
//   ticker: z.string(),
//   industry: z.string(),
//   tertiary_id: z.number(),
//   intrinsic_discount: z.number(),
// });

// export const pBVsIndustryStatementDataSchema = z.object({
//   pb: z.number(),
//   source: z.string(),
//   pb_industry: z.number(),
//   industry_name: z.string(),
// });

// export const pEGStatementDataSchema = z.object({
//   pe: z.number(),
//   peg: z.number().nullable(),
// });

// export const pEVsIndustryStatementDataSchema = z.object({
//   pe: z.number(),
//   pe_industry: z.number(),
//   industry_name: z.string(),
// });

// export const pEVsMarketStatementDataSchema = z.object({
//   pe: z.number(),
//   market: z.string(),
//   pe_market: z.number(),
// });

// export const return1YearVsIndustryStatementDataSchema = z.object({
//   industry: z.string(),
//   ticker_symbol: z.string(),
//   return_1yr_abs: z.number(),
//   flat_return_threshold: z.number(),
//   return_1yr_abs_industry: z.number(),
// });

// export const return1YearVsMarketStatementDataSchema = z.object({
//   market: z.string(),
//   ticker_symbol: z.string(),
//   return_1yr_abs: z.number(),
//   flat_return_threshold: z.number(),
//   return_1yr_abs_market: z.number(),
// });

// export const return30DayVsIndustryStatementDataSchema = z.object({
//   industry: z.string(),
//   return_30d: z.number(),
//   unique_symbol: z.string(),
//   return_30d_industry: z.number(),
//   flat_return_threshold: z.number(),
// });

// export const return30DayVsMarketStatementDataSchema = z.object({
//   market: z.string(),
//   return_30d: z.number(),
//   unique_symbol: z.string(),
//   return_30d_market: z.number(),
//   flat_return_threshold: z.number(),
// });

// export const industrySchema = z.object({
//   name: z.string(),
//   primary_id: z.number(),
//   secondary_id: z.number(),
//   tertiary_id: z.number(),
// });

// export const ceoSchema = z.object({
//   name: z.string(),
//   age: z.number(),
//   url: z.string(),
// });

// export const snowflakeDataSchema = z.object({
//   axes: z.array(z.number()),
//   color: z.number(),
// });

// export const industryAveragesSchema = z.object({
//   industryId: z.number(),
//   countryIso: z.string(),
//   name: z.string(),
//   valueScore: z.number(),
//   dividendsScore: z.number(),
//   futurePerformanceScore: z.number(),
//   healthScore: z.number(),
//   pastPerformanceScore: z.number(),
//   totalScore: z.number(),
//   sharePrice: z.number(),
//   marketCap: z.number(),
//   intrinsicDiscount: z.number(),
//   analystCount: z.number(),
//   PE: z.number(),
//   PB: z.number(),
//   PEG: z.number(),
//   futureOneYearGrowth: z.number(),
//   futureThreeYearGrowth: z.number(),
//   futureOneYearROE: z.null(),
//   futureThreeYearROE: z.null(),
//   pastOneYearGrowth: z.number(),
//   pastFiveYearGrowth: z.number(),
//   ROE: z.number(),
//   ROA: z.number(),
//   dividendYield: z.number(),
//   futureDividendYield: z.number(),
//   payoutRatio: z.null(),
//   EPS: z.number(),
//   insiderBuying: z.number(),
//   debtEquity: z.number(),
//   leveredBeta: z.number(),
//   unleveredBeta: z.number(),
//   totalBaseCount: z.number(),
//   profitableCount: z.number(),
//   analystCoverageCount: z.number(),
//   dividendCount: z.number(),
//   betaCount: z.number(),
//   earningsPerShareGrowthAnnual: z.number(),
//   netIncomeGrowthAnnual: z.number(),
//   cashOpsGrowthAnnual: z.number(),
//   revenueGrowthAnnual: z.number(),
//   leveredBetaMedian: z.number(),
//   baseSource: z.string(),
//   profitableSource: z.string(),
//   analystSource: z.string(),
//   dividendSource: z.string(),
//   betaSource: z.string(),
//   all: allSchema,
// });

// export const analysisHealthSchema = z.object({
//   net_income: z.number(),
//   net_interest_expense: z.number(),
//   cash_operating: z.number(),
//   total_assets: z.number(),
//   ppe: z.number(),
//   inventory: z.number().nullable(),
//   cash_st_investments: z.number(),
//   receivables: z.number(),
//   current_assets: z.number(),
//   total_equity: z.number(),
//   total_debt: z.number(),
//   long_term_debt: z.number().nullable(),
//   long_term_liab: z.number(),
//   accounts_payable: z.number(),
//   total_current_liab: z.number(),
//   total_liab_equity: z.number(),
//   total_debt_equity: z.number(),
//   total_inventory: z.number().nullable(),
//   debt_to_equity_ratio: z.number(),
//   debt_to_equity_ratio_past: z.number().nullable(),
//   net_debt_to_equity: z.number(),
//   assets_equity_ratio: z.number(),
//   fixed_to_total_assets: z.number(),
//   current_assets_to_total_debt: z.number().nullable(),
//   operating_cash_flow_to_total_debt: z.number().nullable(),
//   net_interest_cover: z.number().nullable(),
//   current_solvency_ratio: z.number(),
//   current_assets_to_long_term_liab: z.number(),
//   operating_expenses: z.number(),
//   operating_expenses_total: z.record(z.number()),
//   operating_expenses_growth_annual: z.number().nullable(),
//   operating_expenses_stable_years: z.number().nullable(),
//   operating_expenses_growth_years: z.number().nullable(),
//   median_2yr_net_income: z.number(),
//   industry_analysis: z.union([
//     z.array(z.any()),
//     z.record(z.number().nullable()),
//   ]),
//   capex: z.number().nullable(),
//   capex_growth_1y: z.number().nullable(),
//   capex_growth_annual: z.number().nullable(),
//   net_debt: z.number(),
//   management_rate_return: z.number(),
//   book_value_per_share: z.number(),
//   levered_free_cash_flow: z.number(),
//   levered_free_cash_flow_1y: z.number(),
//   levered_free_cash_flow_2y: z.number(),
//   levered_free_cash_flow_history: z.record(z.number()),
//   levered_free_cash_growth_annual: z.null(),
//   levered_free_cash_flow_growth_annual: z.number(),
//   levered_free_cash_flow_growth_years: z.number().nullable(),
//   levered_free_cash_flow_stable_years: z.number().nullable(),
//   cash_from_investing: z.number(),
//   net_debt_to_ebitda: z.number().nullable(),
//   capitalisation_percent: z.number(),
//   capitalisation_percent_1y: z.number(),
//   cash_operating_growth_1y: z.number(),
//   cash_from_investing_1y: z.number(),
//   inventory_growth_1y: z.number().nullable(),
//   net_operating_assets: z.number().nullable(),
//   net_operating_assets_1y: z.number().nullable(),
//   aggregate_accruals: z.number().nullable(),
//   accounts_receivable_growth_1y: z.number(),
//   accounts_receivable_percent: z.number(),
//   long_term_assets: z.number(),
//   last_balance_sheet_update: z.number(),
//   total_debt_history: z.record(z.number()),
//   current_portion_lease_liabilities: z.number().nullable(),
//   long_term_portion_lease_liabilities: z.number().nullable(),
//   total_lease_liabilities: z.number(),
//   restricted_cash: z.number().nullable(),
//   restricted_cash_ratio: z.number().nullable(),
//   levered_free_cash_flow_break_even_years: z.number().nullable(),
//   net_operating_assets_ltm_history: netOperatingAssetsLtmHistorySchema,
//   aggregate_accruals_ltm_history: aggregateAccrualsLtmHistorySchema,
//   accrual_ratio_from_cashflow_ltm_history:
//     accrualRatioFromCashflowLtmHistorySchema,
//   total_assets_ltm_history: ltmHistorySchema,
//   total_current_liab_ltm_history: ltmHistorySchema,
// });

// export const analysisPastSchema = z.object({
//   revenue: z.number(),
//   revenue_usd: z.number(),
//   revenue_ltm_history: eLtmHistorySchema,
//   operating_revenue: z.number(),
//   net_income: z.number(),
//   net_income_usd: z.number(),
//   net_income_ltm_history: eLtmHistorySchema,
//   earnings_per_share: z.number(),
//   earnings_per_share_ltm_history: eLtmHistorySchema,
//   earnings_per_share_1y: z.number(),
//   earnings_per_share_3y: z.number().nullable(),
//   earnings_per_share_5y: z.number().nullable(),
//   earnings_per_share_5y_avg: z.number(),
//   ebt_excluding: z.number(),
//   earnings_continued_ops: z.number(),
//   total_assets: z.number(),
//   total_equity: z.number(),
//   current_liabilities: z.number(),
//   return_on_equity: z.number(),
//   return_on_assets: z.number(),
//   return_on_capital_employed: z.number(),
//   return_on_capital_employed_past: z.number().nullable(),
//   return_on_capital_growth: z.number().nullable(),
//   earnings_per_share_growth_1y: z.number(),
//   earnings_per_share_growth_3y: z.number(),
//   earnings_per_share_growth_5y: z.number().nullable(),
//   net_income_1y: z.number(),
//   net_income_2y: z.number(),
//   net_income_3y: z.number().nullable(),
//   net_income_4y: z.number().nullable(),
//   net_income_5y: z.number().nullable(),
//   net_income_5y_avg: z.number(),
//   net_income_growth_1y: z.number(),
//   net_income_growth_3y: z.number(),
//   net_income_growth_5y: z.number().nullable(),
//   revenue_growth_1y: z.number(),
//   revenue_growth_3y: z.number(),
//   revenue_growth_5y: z.number().nullable(),
//   days_since_last_update: z.number(),
//   last_earnings_update: z.number(),
//   last_earnings_update_annual: z.number(),
//   industry_analysis: industryAnalysisClassSchema,
//   ebit: z.number(),
//   ebit_ltm_history: ltmHistorySchema,
//   ebit_3y_avg: z.number(),
//   ebit_5y_avg: z.number(),
//   ebit_single_growth_1y: z.number().nullable(),
//   ebit_single_growth_3y: z.number().nullable(),
//   ebit_single_growth_5y: z.number().nullable(),
//   ebit_margin_1y: z.number(),
//   ebit_margin: z.number(),
//   ebitda: z.number().nullable(),
//   ebitda_margin: z.number().nullable(),
//   gross_profit_margin: z.number(),
//   last_filing_date: z.number(),
//   net_income_single_growth_3y: z.number().nullable(),
//   net_income_single_growth_5y: z.number().nullable(),
//   earnings_per_share_single_growth_3y: z.number().nullable(),
//   earnings_per_share_single_growth_5y: z.number().nullable(),
//   gross_profit_margin_1y: z.number(),
//   net_income_margin: z.number(),
//   net_income_margin_1y: z.number(),
//   change_in_unearned_revenue: z.number().nullable(),
//   unearned_revenue_percent_of_sales: z.number(),
//   ebt_including: z.number(),
//   unusual_items: z.number(),
//   unusual_item_ratio: z.number(),
//   operating_revenue_percent: z.number(),
//   years_profitable: z.number(),
//   trading_since_years: z.number(),
//   non_operating_revenue: z.number().nullable(),
//   non_operating_revenue_ratio: z.number().nullable(),
//   non_operating_revenue_ratio_1y: z.number().nullable(),
//   non_operating_revenue_ratio_delta: z.number().nullable(),
//   income_tax_to_ebit_ratio: z.number(),
//   capital_employed_ltm_history: ltmHistorySchema,
//   return_on_capital_employed_ltm_history: ltmHistorySchema,
//   latest_fiscal_year: z.number(),
//   latest_fiscal_quarter: z.number(),
//   business_revenue_segments: z.record(z.number()),
//   geographic_revenue_segments: geographicRevenueSegmentsSchema,
//   selling_general_admin_expense: z.number(),
//   research_development_expense: z.number().nullable(),
//   sales_marketing_expense: z.number().nullable(),
//   stock_based_compensation: z.number().nullable(),
//   depreciation_amortization: z.number().nullable(),
//   general_admin_expense: z.number(),
//   non_operating_expense: z.number(),
//   last_processed_filing_date: z.number().nullable(),
//   last_company_filing_date: z.number().nullable(),
//   last_announced_date: z.number().nullable(),
//   latest_filing_processed: z.boolean().nullable(),
// });

// export const twoStageFcfSchema = z.object({
//   scale: reportingUnitTextSchema,
//   fcf_ltm: z.number(),
//   fcf_data: z.union([z.array(z.any()), z.record(z.number())]),
//   fcf_count: z.union([z.array(z.any()), z.record(z.number())]),
//   first_stage: z.record(firstStageSchema),
//   scale_numeric: z.number(),
//   growth_cagr_5y: z.number(),
//   shares_outstanding: z.number(),
//   capital_to_revenue_ratio_3yr_avg: z.number(),
//   combined_free_cash_flow_time_series: z.record(z.number()),
//   annualized_adjust_free_cash_flow_time_series: z.record(z.number()),
// });

// export const fluffyDividendSchema = z.object({
//   next: z.null(),
//   past: z.union([z.array(z.any()), z.record(pastPastSchema)]),
//   chain: z.record(chainSchema),
// });

// export const currencyInfoSchema = z.object({
//   reporting_unit: z.number(),
//   reporting_unit_abs: z.number(),
//   reporting_unit_text: reportingUnitTextSchema,
//   reporting_currency_iso: currencySchema,
//   reporting_unit_text_abs: reportingUnitTextSchema,
//   reporting_currency_symbol: currencySymbolSchema,
//   trading_item_currency_iso: currencySchema,
//   trading_item_currency_symbol: currencySymbolSchema,
//   primary_trading_item_currency_iso: currencySchema,
//   primary_trading_item_currency_symbol: currencySymbolSchema,
// });

// export const industriesSchema = z.object({
//   sector: primarySchema,
//   primary: primarySchema,
//   tertiary: tertiarySchema,
//   secondary: primarySchema,
// });

// export const nIEstSchema = z.object({
//   id: nIEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const fcfEstSchema = z.object({
//   id: fcfEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const navEstSchema = z.object({
//   id: navEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const ebitdaEstSchema = z.object({
//   id: ebitdaEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const nINumEstSchema = z.object({
//   id: nINumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const estActRevSchema = z.object({
//   id: estActRevIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const fcfNumEstSchema = z.object({
//   id: fcfNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const navNumEstSchema = z.object({
//   id: navNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const revenueEstSchema = z.object({
//   id: revenueEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const bvShareEstSchema = z.object({
//   id: bvShareEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const epsNormEstSchema = z.object({
//   id: epsNormEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const cashOperEstSchema = z.object({
//   id: cashOperEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const estActEbitdaSchema = z.object({
//   id: estActEbitdaIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const nIReportedEstSchema = z.object({
//   id: nIReportedEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const revenueLowEstSchema = z.object({
//   id: revenueLowEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const revenueNumEstSchema = z.object({
//   id: revenueNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const bvShareNumEstSchema = z.object({
//   id: bvShareNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const epsNormNumEstSchema = z.object({
//   id: epsNormNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const epsReportedEstSchema = z.object({
//   id: epsReportedEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const grossMarginEstSchema = z.object({
//   id: grossMarginEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const revenueHighEstSchema = z.object({
//   id: revenueHighEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const cashOperNumEstSchema = z.object({
//   id: cashOperNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const returnEquityEstSchema = z.object({
//   id: returnEquityEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const estActNIReportedSchema = z.object({
//   id: estActNIReportedIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const nIReportedLowEstSchema = z.object({
//   id: nIReportedLowEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const nIReportedNumEstSchema = z.object({
//   id: nIReportedNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const epsReportedLowEstSchema = z.object({
//   id: epsReportedLowEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const epsReportedNumEstSchema = z.object({
//   id: epsReportedNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const estActEpsReportedSchema = z.object({
//   id: estActEpsReportedIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const nIReportedHighEstSchema = z.object({
//   id: nIReportedHighEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const epsReportedHighEstSchema = z.object({
//   id: epsReportedHighEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const returnEquityNumEstSchema = z.object({
//   id: returnEquityNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const dpsEstSchema = z.object({
//   id: dpsEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const dpsNumEstSchema = z.object({
//   id: dpsNumEstIDSchema,
//   unit: reportingUnitTextSchema,
//   value: z.number(),
//   currency: z.null(),
//   end_date: z.number(),
//   unit_numeric: z.number(),
//   effective_date: z.number(),
// });

// export const the3Schema = z.object({
//   buy: the3BuySchema,
//   sell: the3BuySchema,
// });

// export const the1BuySchema = z.object({
//   avg_price: z.number(),
//   month_diff: z.number(),
//   trade_type: traTypeSchema,
//   security_id: z.number(),
//   total_shares: z.number(),
//   total_trades: z.number(),
//   company_names: z.array(z.any()),
//   unique_owners: z.number(),
//   individual_ids: z.array(z.number()),
//   individual_names: z.array(z.string()),
//   total_trans_value: z.number(),
//   total_company_shares: z.number(),
//   total_individual_shares: z.number(),
// });

// export const sellSchema = z.object({
//   avg_price: z.number(),
//   month_diff: z.number(),
//   trade_type: traTypeSchema,
//   security_id: z.number(),
//   total_shares: z.number(),
//   total_trades: z.number(),
//   company_names: z.array(z.any()),
//   unique_owners: z.number(),
//   individual_ids: z.array(z.any()),
//   individual_names: z.array(z.any()),
//   total_trans_value: z.number(),
//   total_company_shares: z.number(),
//   total_individual_shares: z.number(),
// });

// export const datumSchema = z.object({
//   transaction_id: z.number(),
//   transaction_type: traTypeSchema,
//   transaction_type_id: z.number(),
//   transaction_type_description: transactionTypeDescriptionSchema,
//   owner_object_id: z.number(),
//   owner_name: z.string(),
//   owner_type: ownerTypeSchema,
//   management_insider: z.boolean(),
//   trade_date_min: z.number(),
//   trade_date_max: z.number(),
//   shares: z.number(),
//   price_min: z.number(),
//   price_max: z.number(),
//   transaction_value: z.number(),
//   percentage_shares_traded: z.number(),
//   percentage_change_trans_shares: z.number().nullable(),
//   filing_end_shares: z.number(),
//   filing_date: z.number(),
//   month_diff: z.number(),
// });

// export const listingSchema = z.object({
//   start_date: z.number(),
//   security_id: z.number(),
//   currency_iso: currencySchema,
//   canonical_url: z.string(),
//   exchange_name: exchangeNameSchema,
//   security_name: z.string(),
//   ticker_symbol: z.string(),
//   major_currency: z.boolean(),
//   currency_symbol: currencySymbolSchema,
//   exchange_symbol: exchangeSymbolSchema,
//   trading_item_id: z.number(),
//   primary_security: z.boolean(),
//   security_type_id: z.number(),
//   exchange_country_iso: countrySchema,
//   primary_trading_item: z.boolean(),
//   exchange_currency_iso: currencySchema,
//   exchange_country_iso_3: exchangeCountryISO3Schema,
//   exchange_currency_symbol: currencySymbolSchema,
//   exchange_importance_level: z.number(),
// });

// export const leaderSchema = z.object({
//   id: z.number(),
//   age: z.number(),
//   rank: z.number(),
//   title: z.string(),
//   prefix: prefixSchema,
//   pro_id: z.number(),
//   suffix: z.null(),
//   tenure: z.number().nullable(),
//   key_exec: z.boolean(),
//   only_one: z.boolean(),
//   pro_rank: z.number(),
//   biography: z.string(),
//   last_name: z.string(),
//   pro_title: z.string(),
//   specialty: z.null(),
//   year_born: z.number(),
//   board_flag: z.boolean(),
//   board_rank: z.number(),
//   first_name: z.string(),
//   pro_member: z.boolean(),
//   salutation: z.string(),
//   start_date: z.number().nullable(),
//   currency_id: z.null(),
//   middle_name: z.string(),
//   shares_held: z.number(),
//   short_title: z.string(),
//   board_member: z.boolean(),
//   compensation: z.null(),
//   holding_date: z.number(),
//   options_held: z.number(),
//   top_key_exec: z.boolean(),
//   compensations: z.array(z.any()),
//   shares_changed: z.number(),
//   rank_shares_held: z.number().nullable(),
//   rank_shares_sold: z.null(),
//   rank_shares_bought: z.null(),
//   percent_shares_changed: z.number(),
//   percent_of_shares_outstanding: z.number(),
// });

// export const boardSchema = z.object({
//   id: z.number(),
//   age: z.number(),
//   rank: z.number(),
//   title: z.string(),
//   prefix: prefixSchema,
//   pro_id: z.number(),
//   suffix: z.string().nullable(),
//   tenure: z.number().nullable(),
//   key_exec: z.boolean(),
//   only_one: z.boolean(),
//   pro_rank: z.number().nullable(),
//   biography: z.string(),
//   last_name: z.string(),
//   pro_title: proTitleSchema,
//   specialty: z.null(),
//   year_born: z.number(),
//   board_flag: z.boolean(),
//   board_rank: z.number(),
//   first_name: z.string(),
//   pro_member: z.boolean(),
//   salutation: z.string(),
//   start_date: z.number().nullable(),
//   middle_name: z.string().nullable(),
//   shares_held: z.number().nullable(),
//   short_title: z.string(),
//   board_member: z.boolean(),
//   compensation: z.number().nullable(),
//   holding_date: z.number().nullable(),
//   options_held: z.number().nullable(),
//   top_key_exec: z.boolean(),
//   shares_changed: z.number().nullable(),
//   rank_shares_held: z.number().nullable(),
//   rank_shares_sold: z.null(),
//   rank_shares_bought: z.number().nullable(),
//   percent_shares_changed: z.number().nullable(),
//   compensation_currency_iso: currencySchema.optional(),
//   percent_of_shares_outstanding: z.number().nullable(),
//   currency_id: z.null().optional(),
// });

// export const purplePastSchema = z.object({
//   id: pastIDSchema,
//   unit: reportingUnitTextSchema,
//   year: z.number(),
//   value: z.number(),
//   latest: z.boolean(),
//   quarter: z.number(),
//   type_id: z.number(),
//   currency: currencySchema,
//   end_date: z.number(),
//   unit_numeric: z.number(),
// });

// export const returnMetadataSchema = z.object({
//   return_90d: return90DSchema,
// });

// export const growthStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: growthStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const payoutStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: payoutStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const payoutStatement3YSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: payoutStatement3YDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const volatilityStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: volatilityStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const yieldLowRiskStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: yieldLowRiskStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const yieldMarketTopStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: yieldMarketTopStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const cash2YStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: cash2YStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const earningsSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: earningsHighGrowthDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const earningsVsMarketAverageSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: earningsVsMarketAverageDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const fundamentalGrowthMethodStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.null(),
//   data: fundamentalGrowthMethodStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const growth1YStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: growth1YStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const growth3YStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: growth3YStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const netIncome2YStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: netIncome2YStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const projectedROEBenchStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: projectedROEBenchStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const projectedROEIndustryStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: projectedROEIndustryStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const projectedROEStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: projectedROEStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const revenue2YStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: revenue2YStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const revenueHighGrowthSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: revenueHighGrowthDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const revenueVsMarketAverageSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: revenueVsMarketAverageDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const assetsToLiabsStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: assetsToLiabsStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const cashBurnGrowthStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: cashBurnGrowthStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const cashBurnStableStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: cashBurnStableStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const cashDebtStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: cashDebtStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const currentAssetsToDebtStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: currentAssetsToDebtStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const currentAssetsToLTLiabsStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: currentAssetsToLTLiabsStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const debtGrowthStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: debtGrowthStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const debtInterestStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: debtInterestStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const debtStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: debtStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const inventoryStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: inventoryStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const meaninglessHealthStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: meaninglessHealthStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const boardTenureStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: boardTenureStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const cEOOverCompensationStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: cEOOverCompensationStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const cEOSalaryGrowthStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: cEOSalaryGrowthStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const insiderTradeStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: insiderTradeStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const proTenureStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: proTenureStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const analystCoverageStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string().nullable(),
//   data: analystCoverageStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const exchangeTradedFundStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.null(),
//   data: exchangeTradedFundStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const marketCapStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.null(),
//   data: marketCapStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const outDatedDataStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string().nullable(),
//   data: outDatedDataStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const priceVolatilityStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string().nullable(),
//   data: priceVolatilityStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const tradingHaltStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.null(),
//   data: tradingHaltStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const growth1Y5YStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: growth1Y5YStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const growth5YStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: growth5YStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const meaninglessPastStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: meaninglessPastStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const rOAStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: rOAStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const rOCEStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: rOCEStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const rOEStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: rOEStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const vsMarketGrowthStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: vsMarketGrowthStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const intrinsicStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: intrinsicStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const meaninglessDCFStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: meaninglessDCFStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const pBVsIndustryStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: pBVsIndustryStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const pEGStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: pEGStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const pEVsIndustryStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: pEVsIndustryStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const pEVsMarketStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: pEVsMarketStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const return1YearVsIndustryStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: return1YearVsIndustryStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const return1YearVsMarketStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: return1YearVsMarketStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const return30DayVsIndustryStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: return30DayVsIndustryStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const return30DayVsMarketStatementSchema = z.object({
//   statement_name: z.string(),
//   area: z.string(),
//   date_generated: z.number(),
//   is_score: z.boolean(),
//   description: z.string(),
//   data: return30DayVsMarketStatementDataSchema,
//   type: z.string(),
//   latex_formula: z.null(),
// });

// export const infoDataSchema = z.object({
//   id: z.string(),
//   description: z.string(),
//   warning_type: z.number(),
//   industry: industrySchema,
//   fund: z.boolean(),
//   status: z.string(),
//   currency: currencySchema,
//   country: countrySchema,
//   employees: z.number(),
//   address: z.string(),
//   year_founded: z.number().nullable(),
//   url: z.string(),
//   logo_url: z.string(),
//   cover_url: z.string(),
//   cover_small_url: z.string(),
//   ceo: ceoSchema,
//   legal_name: z.string(),
//   main_thumb: z.string().nullable(),
//   main_header: z.string().nullable(),
// });

// export const snowflakeSchema = z.object({
//   data: snowflakeDataSchema,
// });

// export const infoSchema = z.object({
//   data: infoDataSchema,
// });

// export const intrinsicValueSchema = z.object({
//   de: z.number(),
//   iso: countrySchema,
//   npv: z.number(),
//   REIT: z.null(),
//   pvtv: z.number(),
//   model: z.string(),
//   pv_5y: z.number(),
//   tax_rate: z.number(),
//   asset_based: z.null(),
//   levered_beta: z.number(),
//   adr_per_share: z.number(),
//   npv_per_share: z.number(),
//   two_stage_fcf: twoStageFcfSchema,
//   cost_of_equity: z.number(),
//   equity_premium: z.number(),
//   excess_returns: z.null(),
//   risk_free_rate: z.number(),
//   terminal_value: z.number(),
//   unlevered_beta: z.number(),
//   dividend_discount: dividendDiscountSchema,
//   intrinsic_discount: z.number().nullable(),
//   levered_beta_actual: z.number(),
//   npv_per_share_reported_currency: z.number().optional(),
// });

// export const pricesSchema = z.object({
//   history: z.record(historySchema),
//   listing: z.number(),
//   primary: z.number(),
//   return_metadata: returnMetadataSchema,
//   listing_currrency_primary: z.number(),
//   primary_currrency_listing: z.number(),
//   listing_currrency_reported: z.number(),
//   primary_currrency_reported: z.number(),
// });

// export const membersSchema = z.object({
//   board: z.record(boardSchema),
//   leader: leaderSchema,
//   management: z.record(managementValueSchema),
// });

// export const insiderTransactionsSchema = z.object({
//   data: z.array(datumSchema),
// });

// export const estimateSchema = z.object({
//   ni_est: nIEstSchema.optional(),
//   fcf_est: fcfEstSchema.optional(),
//   nav_est: navEstSchema.optional(),
//   ebitda_est: ebitdaEstSchema.optional(),
//   ni_num_est: nINumEstSchema.optional(),
//   est_act_rev: estActRevSchema.optional(),
//   fcf_num_est: fcfNumEstSchema.optional(),
//   nav_num_est: navNumEstSchema.optional(),
//   revenue_est: revenueEstSchema.optional(),
//   bv_share_est: bvShareEstSchema.optional(),
//   eps_norm_est: epsNormEstSchema.optional(),
//   cash_oper_est: cashOperEstSchema.optional(),
//   est_act_ebitda: estActEbitdaSchema.optional(),
//   ni_reported_est: nIReportedEstSchema.optional(),
//   revenue_low_est: revenueLowEstSchema.optional(),
//   revenue_num_est: revenueNumEstSchema.optional(),
//   bv_share_num_est: bvShareNumEstSchema.optional(),
//   eps_norm_num_est: epsNormNumEstSchema.optional(),
//   eps_reported_est: epsReportedEstSchema.optional(),
//   gross_margin_est: grossMarginEstSchema.optional(),
//   revenue_high_est: revenueHighEstSchema.optional(),
//   cash_oper_num_est: cashOperNumEstSchema.optional(),
//   return_equity_est: returnEquityEstSchema.optional(),
//   est_act_ni_reported: estActNIReportedSchema.optional(),
//   ni_reported_low_est: nIReportedLowEstSchema.optional(),
//   ni_reported_num_est: nIReportedNumEstSchema.optional(),
//   eps_reported_low_est: epsReportedLowEstSchema.optional(),
//   eps_reported_num_est: epsReportedNumEstSchema.optional(),
//   est_act_eps_reported: estActEpsReportedSchema.optional(),
//   ni_reported_high_est: nIReportedHighEstSchema.optional(),
//   eps_reported_high_est: epsReportedHighEstSchema.optional(),
//   return_equity_num_est: returnEquityNumEstSchema.optional(),
//   dps_est: dpsEstSchema.optional(),
//   dps_num_est: dpsNumEstSchema.optional(),
//   price_target_est: priceTargetEstSchema.optional(),
//   price_target_low_est: priceTargetEstSchema.optional(),
//   price_target_num_est: tNumEstSchema.optional(),
//   price_target_std_est: priceTargetEstSchema.optional(),
//   price_target_high_est: priceTargetEstSchema.optional(),
//   ffo_adj_reit_est: ffoAdjReitEstSchema.optional(),
//   ffo_adj_reit_num_est: tNumEstSchema.optional(),
// });

// export const the1Schema = z.object({
//   buy: the1BuySchema,
//   sell: sellSchema,
// });

// export const the4Schema = z.object({
//   buy: the1BuySchema,
//   sell: the1BuySchema,
// });

// export const statementsDividendSchema = z.object({
//   GrowthStatement: growthStatementSchema,
//   PayoutStatement: payoutStatementSchema,
//   PayoutStatement3y: payoutStatement3YSchema,
//   VolatilityStatement: volatilityStatementSchema,
//   YieldLowRiskStatement: yieldLowRiskStatementSchema,
//   YieldMarketTopStatement: yieldMarketTopStatementSchema,
// });

// export const statementsFutureSchema = z.object({
//   Cash2yStatement: cash2YStatementSchema,
//   EarningsHighGrowth: earningsSchema,
//   EarningsVsMarketAverage: earningsVsMarketAverageSchema,
//   EarningsVsRiskFreeRate: earningsSchema,
//   FundamentalGrowthMethodStatement: fundamentalGrowthMethodStatementSchema,
//   Growth1yStatement: growth1YStatementSchema,
//   Growth3yStatement: growth3YStatementSchema,
//   MeaninglessFutureStatement: meaninglessFutureStatementSchema,
//   NetIncome2yStatement: netIncome2YStatementSchema,
//   ProjectedROEBenchStatement: projectedROEBenchStatementSchema,
//   ProjectedROEIndustryStatement: projectedROEIndustryStatementSchema,
//   ProjectedROEStatement: projectedROEStatementSchema,
//   Revenue2yStatement: revenue2YStatementSchema,
//   RevenueHighGrowth: revenueHighGrowthSchema,
//   RevenueVsMarketAverage: revenueVsMarketAverageSchema,
// });

// export const statementsHealthSchema = z.object({
//   AssetsToLiabsStatement: assetsToLiabsStatementSchema,
//   CashBurnGrowthStatement: cashBurnGrowthStatementSchema,
//   CashBurnStableStatement: cashBurnStableStatementSchema,
//   CashDebtStatement: cashDebtStatementSchema,
//   CurrentAssetsToDebtStatement: currentAssetsToDebtStatementSchema,
//   CurrentAssetsToLTLiabsStatement: currentAssetsToLTLiabsStatementSchema,
//   DebtGrowthStatement: debtGrowthStatementSchema,
//   DebtInterestStatement: debtInterestStatementSchema,
//   DebtStatement: debtStatementSchema,
//   InventoryStatement: inventoryStatementSchema,
//   MeaninglessHealthStatement: meaninglessHealthStatementSchema,
// });

// export const statementsManagementSchema = z.object({
//   BoardTenureStatement: boardTenureStatementSchema,
//   CEOOverCompensationStatement: cEOOverCompensationStatementSchema,
//   CEOSalaryGrowthStatement: cEOSalaryGrowthStatementSchema,
//   InsiderTradeStatement: insiderTradeStatementSchema,
//   ProTenureStatement: proTenureStatementSchema,
// });

// export const statementsMiscSchema = z.object({
//   AnalystCoverageStatement: analystCoverageStatementSchema,
//   ExchangeTradedFundStatement: exchangeTradedFundStatementSchema,
//   MarketCapStatement: marketCapStatementSchema,
//   OutDatedDataStatement: outDatedDataStatementSchema,
//   PriceVolatilityStatement: priceVolatilityStatementSchema,
//   TradingHaltStatement: tradingHaltStatementSchema,
// });

// export const statementsPastSchema = z.object({
//   Growth1y5yStatement: growth1Y5YStatementSchema,
//   Growth5yStatement: growth5YStatementSchema,
//   MeaninglessPastStatement: meaninglessPastStatementSchema,
//   ROAStatement: rOAStatementSchema,
//   ROCEStatement: rOCEStatementSchema,
//   ROEStatement: rOEStatementSchema,
//   VsMarketGrowthStatement: vsMarketGrowthStatementSchema,
// });

// export const statementsValueSchema = z.object({
//   IntrinsicStatement: intrinsicStatementSchema,
//   IntrinsicUberStatement: intrinsicStatementSchema,
//   MeaninglessDCFStatement: meaninglessDCFStatementSchema,
//   PBVsIndustryStatement: pBVsIndustryStatementSchema,
//   PEGStatement: pEGStatementSchema,
//   PEVsIndustryStatement: pEVsIndustryStatementSchema,
//   PEVsMarketStatement: pEVsMarketStatementSchema,
//   Return1yearVsIndustryStatement: return1YearVsIndustryStatementSchema,
//   Return1yearVsMarketStatement: return1YearVsMarketStatementSchema,
//   Return30dayVsIndustryStatement: return30DayVsIndustryStatementSchema,
//   Return30dayVsMarketStatement: return30DayVsMarketStatementSchema,
// });

// export const scoreDataSchema = z.object({
//   value: z.number(),
//   income: z.number(),
//   health: z.number(),
//   past: z.number(),
//   future: z.number(),
//   management: z.number(),
//   misc: z.number(),
//   total: z.number(),
//   sentence: z.string(),
//   snowflake: snowflakeSchema,
// });

// export const scoreSchema = z.object({
//   data: scoreDataSchema,
// });

// export const statementsClassSchema = z.object({
//   dividend: statementsDividendSchema,
//   future: statementsFutureSchema,
//   health: statementsHealthSchema,
//   management: statementsManagementSchema,
//   misc: statementsMiscSchema,
//   past: statementsPastSchema,
//   value: statementsValueSchema,
// });

// export const analysisValueSchema = z.object({
//   pe: z.number(),
//   pb: z.number(),
//   peg: z.number().nullable(),
//   beta_5y: z.number().nullable(),
//   beta_5y_unlevered: z.number().nullable(),
//   intrinsic_discount: z.number().nullable(),
//   npv_per_share: z.number().nullable(),
//   earnings_per_share_growth_1y: z.null(),
//   merged_future_earnings_per_share: z.array(z.any()),
//   intrinsic_value: intrinsicValueSchema,
//   industry_analysis: z.array(z.any()),
//   market_cap_usd: z.number(),
//   market_cap: z.number(),
//   market_cap_band: z.string(),
//   last_share_price: z.number(),
//   price_to_sales: z.number(),
//   ev_to_sales: z.number(),
//   ev_to_ebitda: z.number().nullable(),
//   return_1d: z.number(),
//   return_7d: z.number(),
//   return_30d: z.number(),
//   return_90d: z.number(),
//   return_ytd: z.number(),
//   return_1yr_abs: z.number().nullable(),
//   return_3yr_abs: z.number().nullable(),
//   return_5yr_abs: z.number().nullable(),
//   return_7d_total_return: z.number(),
//   return_30d_total_return: z.number(),
//   return_90d_total_return: z.number(),
//   return_ytd_total_return: z.number(),
//   return_1yr_total_return: z.number().nullable(),
//   return_3yr_total_return: z.number().nullable(),
//   return_5yr_total_return: z.number().nullable(),
//   return_since_ipo_abs: z.number(),
//   price_target: z.number().nullable(),
//   price_target_low: z.number().nullable(),
//   price_target_high: z.number().nullable(),
//   price_target_analyst_count: z.number(),
//   market_cap_movement_1d: z.number(),
//   market_cap_movement_usd_1d: z.number(),
//   market_cap_movement_7d: z.number(),
//   market_cap_movement_usd_7d: z.number(),
//   market_cap_movement_30d: z.number(),
//   market_cap_movement_usd_30d: z.number(),
//   market_cap_movement_90d: z.number(),
//   market_cap_movement_usd_90d: z.number(),
//   market_cap_movement_1y: z.number().nullable(),
//   market_cap_movement_usd_1y: z.number().nullable(),
//   market_cap_movement_3y: z.number().nullable(),
//   market_cap_movement_usd_3y: z.number().nullable(),
//   market_cap_movement_5y: z.number().nullable(),
//   market_cap_movement_usd_5y: z.number().nullable(),
// });

// export const insiderTradingSchema = z.object({
//   '1': the1Schema,
//   '2': the1Schema,
//   '3': the3Schema,
//   '4': the4Schema,
//   total_buy: z.number(),
//   total_sell: z.number(),
//   total_volume: z.number(),
// });

// export const fluffyAnalysisSchema = z.object({
//   dividend: analysisDividendSchema,
//   future: analysisFutureSchema,
//   health: analysisHealthSchema,
//   management: analysisManagementSchema,
//   misc: analysisMiscSchema,
//   past: analysisPastSchema,
//   value: analysisValueSchema,
// });

// export const rawDataDataSchema = z.object({
//   company_info: companyInfoSchema,
//   market_cap: marketCapSchema,
//   listings: z.record(listingSchema),
//   prices: pricesSchema,
//   dividend: fluffyDividendSchema,
//   past: z.record(z.record(purplePastSchema)),
//   estimates: z.union([z.array(z.any()), z.record(estimateSchema)]),
//   members: membersSchema,
//   insider_trading: insiderTradingSchema,
//   ownership: z.record(ownershipSchema),
//   currency_info: currencyInfoSchema,
//   industries: industriesSchema,
//   insider_transactions: insiderTransactionsSchema,
// });

// export const rawDataSchema = z.object({
//   data: rawDataDataSchema,
// });

// export const extendedDataSchema = z.object({
//   id: z.string(),
//   analysis: fluffyAnalysisSchema,
//   statements: z.union([z.array(z.any()), statementsClassSchema]),
//   scores: scoresSchema,
//   industry_averages: industryAveragesSchema,
//   raw_data: rawDataSchema,
// });

// export const extendedSchema = z.object({
//   data: extendedDataSchema,
// });

// export const analysisDataSchema = z.object({
//   id: z.string(),
//   share_price: z.number(),
//   market_cap: z.number(),
//   intrinsic_discount: z.number().nullable(),
//   pe: z.number(),
//   pb: z.number(),
//   peg: z.number().nullable(),
//   preferred_multiple: z.string(),
//   preferred_multiple_reason: z.string(),
//   preferred_multiple_secondary: z.string(),
//   preferred_relative_multiple_average_peer_value: z.number(),
//   justified_preferred_multiple_ratio: z.number().nullable(),
//   roe: z.number(),
//   roa: z.number(),
//   eps: z.number(),
//   debt_equity: z.number(),
//   dividend: purpleDividendSchema,
//   future: dataFutureSchema,
//   past: fluffyPastSchema,
//   analyst_count: z.number().nullable(),
//   insider_buying: z.number().nullable(),
//   show_new_valuation: z.boolean(),
//   show_analyst_price_target: z.boolean(),
//   show_new_apt_calc: z.boolean(),
//   extended: extendedSchema,
// });

// export const purpleAnalysisSchema = z.object({
//   data: analysisDataSchema,
// });

// export const swsCrawlCompanyDataDataSchema = z.object({
//   id: z.number(),
//   company_id: z.string(),
//   company_status: z.number(),
//   trading_item_id: z.number(),
//   trading_item_status: z.number(),
//   name: z.string(),
//   slug: z.string(),
//   exchange_symbol: exchangeSymbolSchema,
//   ticker_symbol: z.string(),
//   unique_symbol: z.string(),
//   primary_ticker: z.boolean(),
//   last_updated: z.number(),
//   canonical_url: z.string(),
//   primary_canonical_url: z.string(),
//   is_searchable: z.boolean(),
//   isin_symbol: z.string(),
//   active: z.boolean(),
//   classification_status: z.string(),
//   analysis: purpleAnalysisSchema,
//   info: infoSchema,
//   score: scoreSchema,
// });

// export const swsCrawlCompanyDataSchema = z.object({
//   data: swsCrawlCompanyDataDataSchema,
// });
